# docker-compose file managing Nginx and the application
# Loading some variables from the .env file:
#   - DOMAIN: DNS domain name
#   - EMAIL: Maintainer email
#   - APP_FOLDER: Directory containing the application
#   - FLASK_APP: Flask entrypoint
#   - FLASK_ENV: Flask environment

version: "3.2"

services:
  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
        FLASK: application
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - application
    restart: unless-stopped

  application:
    build: ./${APP_FOLDER}
    build: ./${APP_FOLDER}
    restart: unless-stopped
    #command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - TZ=Asia/Kolkata
    ports:
      - 5000:5000

  application1:
    build: ./${APP_FOLDER}
    build: ./${APP_FOLDER}
    restart: unless-stopped
    #command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - TZ=Asia/Kolkata
    ports:
      - 5001:5000

  application2:
    build: ./${APP_FOLDER}
    build: ./${APP_FOLDER}
    restart: unless-stopped
    #command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - TZ=Asia/Kolkata
    ports:
      - 5002:5000

  application3:
    build: ./${APP_FOLDER}
    build: ./${APP_FOLDER}
    restart: unless-stopped
    #command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - TZ=Asia/Kolkata
    ports:
      - 5003:5000

  application4:
    build: ./${APP_FOLDER}
    build: ./${APP_FOLDER}
    restart: unless-stopped
    #command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - TZ=Asia/Kolkata
    ports:
      - 5004:5000

  application5:
    build: ./${APP_FOLDER}
    build: ./${APP_FOLDER}
    restart: unless-stopped
    #command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - TZ=Asia/Kolkata
    ports:
      - 5005:5000

  application6:
    build: ./${APP_FOLDER}
    build: ./${APP_FOLDER}
    restart: unless-stopped
    #command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - TZ=Asia/Kolkata
    ports:
      - 5006:5000

  application7:
    build: ./${APP_FOLDER}
    build: ./${APP_FOLDER}
    restart: unless-stopped
    #command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - TZ=Asia/Kolkata
    ports:
      - 5007:5000

  application8:
    build: ./${APP_FOLDER}
    build: ./${APP_FOLDER}
    restart: unless-stopped
    #command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - TZ=Asia/Kolkata
    ports:
      - 5008:5000

  application9:
    build: ./${APP_FOLDER}
    build: ./${APP_FOLDER}
    restart: unless-stopped
    #command: gunicorn --bind 0.0.0.0:5000 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - TZ=Asia/Kolkata
    ports:
      - 5009:5000